---
- name: restart_sshd
  service:
    name: sshd
    state: restarted

# Handler for cleaning up yum cache when repo files change
- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no
